# Generated by Django 2.2.4 on 2023-01-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pypie_derby_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pies', to='pypie_derby_app.User'),
        ),
    ]
